### ISSUE TITLE
`/usr/bin/env bash` doesn't recognize --posix argument on Ubuntu 

### ISSUE THREAD

**Issue by siddharth-krishna** [michael-emmi/2up#1]
On Ubuntu 14.04, I get the following error:
```
/usr/bin/env: bash --posix: No such file or directory
```

The error disappears if I remove the `--posix` flag.

**Comment by michael-emmi** [comment]
Interesting, I hadn’t realized “shebang” was so non-standard:

https://stackoverflow.com/questions/4303128/how-to-use-multiple-arguments-for-awk-with-a-shebang-i-e
